spring.application.name=consulta-cep
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_HOST_PORT:55432}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

consulta-cep.api-externa.base-url=http://localhost:${WIREMOCK_HOST_PORT:8081}
